### ISSUE TITLE
ERROR: No matching distribution found for lilripper

### ISSUE THREAD

**Issue by Saidis00** [pauliusbaulius/lil_ripper#1]
Keep getting this error on install, any ideas?
Thanks in advance! 

root@Saiarch:~# pip3 install lilripper
Collecting lilripper
  ERROR: Could not find a version that satisfies the requirement lilripper (from versions: none)
ERROR: No matching distribution found for lilripper

**Comment by pauliusbaulius** [comment]
Because I set distribution as Linux only, are you trying to install it on Windows, Mac machine?

**Comment by Saidis00** [comment]
Nah, I'm using Ubuntu, I got it working though
